load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "MyLibrary",
    srcs = ["Foo.cpp"],
    hdrs = ["Foo.h"],
    # Mirror CMake's include_directories(src/Libraries): consumers include
    # "MyLibrary/Foo.h".
    include_prefix = "MyLibrary",
    visibility = ["//visibility:public"],
)
